name: CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Check gofmt
        run: test -z "$(gofmt -s -d .)"

      - name: Run go vet
        run: go vet ./...

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Test
        run: make test-unit